// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "",
    // directUrl is used for migrations with pooled connections (Vercel Postgres / Supabase)
    // Uncomment when using a pooler:
    // directUrl: process.env["DATABASE_URL_UNPOOLED"] ?? "",
  },
});
