import { Continent } from "@prisma/client";

export const ALL_COUNTRIES: { code: string; name: string; continent: Continent }[] = [
  // EUROPE
  { code: "ALB", name: "Albania", continent: "EUROPE" },
  { code: "AND", name: "Andorra", continent: "EUROPE" },
  { code: "ARM", name: "Armenia", continent: "EUROPE" },
  { code: "AUT", name: "Austria", continent: "EUROPE" },
  { code: "AZE", name: "Azerbaijan", continent: "EUROPE" },
  { code: "BLR", name: "Belarus", continent: "EUROPE" },
  { code: "BEL", name: "Belgium", continent: "EUROPE" },
  { code: "BIH", name: "Bosnia and Herzegovina", continent: "EUROPE" },
  { code: "BGR", name: "Bulgaria", continent: "EUROPE" },
  { code: "HRV", name: "Croatia", continent: "EUROPE" },
  { code: "CYP", name: "Cyprus", continent: "EUROPE" },
  { code: "CZE", name: "Czech Republic", continent: "EUROPE" },
  { code: "DNK", name: "Denmark", continent: "EUROPE" },
  { code: "EST", name: "Estonia", continent: "EUROPE" },
  { code: "FIN", name: "Finland", continent: "EUROPE" },
  { code: "FRA", name: "France", continent: "EUROPE" },
  { code: "GEO", name: "Georgia", continent: "EUROPE" },
  { code: "DEU", name: "Germany", continent: "EUROPE" },
  { code: "GRC", name: "Greece", continent: "EUROPE" },
  { code: "HUN", name: "Hungary", continent: "EUROPE" },
  { code: "ISL", name: "Iceland", continent: "EUROPE" },
  { code: "IRL", name: "Ireland", continent: "EUROPE" },
  { code: "ITA", name: "Italy", continent: "EUROPE" },
  { code: "LVA", name: "Latvia", continent: "EUROPE" },
  { code: "LIE", name: "Liechtenstein", continent: "EUROPE" },
  { code: "LTU", name: "Lithuania", continent: "EUROPE" },
  { code: "LUX", name: "Luxembourg", continent: "EUROPE" },
  { code: "MLT", name: "Malta", continent: "EUROPE" },
  { code: "MDA", name: "Moldova", continent: "EUROPE" },
  { code: "MCO", name: "Monaco", continent: "EUROPE" },
  { code: "MNE", name: "Montenegro", continent: "EUROPE" },
  { code: "NLD", name: "Netherlands", continent: "EUROPE" },
  { code: "MKD", name: "North Macedonia", continent: "EUROPE" },
  { code: "NOR", name: "Norway", continent: "EUROPE" },
  { code: "POL", name: "Poland", continent: "EUROPE" },
  { code: "PRT", name: "Portugal", continent: "EUROPE" },
  { code: "ROU", name: "Romania", continent: "EUROPE" },
  { code: "RUS", name: "Russia", continent: "EUROPE" },
  { code: "SMR", name: "San Marino", continent: "EUROPE" },
  { code: "SRB", name: "Serbia", continent: "EUROPE" },
  { code: "SVK", name: "Slovakia", continent: "EUROPE" },
  { code: "SVN", name: "Slovenia", continent: "EUROPE" },
  { code: "ESP", name: "Spain", continent: "EUROPE" },
  { code: "SWE", name: "Sweden", continent: "EUROPE" },
  { code: "CHE", name: "Switzerland", continent: "EUROPE" },
  { code: "TUR", name: "Turkey", continent: "EUROPE" },
  { code: "UKR", name: "Ukraine", continent: "EUROPE" },
  { code: "GBR", name: "United Kingdom", continent: "EUROPE" },
  { code: "VAT", name: "Vatican City", continent: "EUROPE" },
  { code: "XKX", name: "Kosovo", continent: "EUROPE" },
  // ASIA
  { code: "AFG", name: "Afghanistan", continent: "ASIA" },
  { code: "BHR", name: "Bahrain", continent: "ASIA" },
  { code: "BGD", name: "Bangladesh", continent: "ASIA" },
  { code: "BTN", name: "Bhutan", continent: "ASIA" },
  { code: "BRN", name: "Brunei", continent: "ASIA" },
  { code: "KHM", name: "Cambodia", continent: "ASIA" },
  { code: "CHN", name: "China", continent: "ASIA" },
  { code: "IND", name: "India", continent: "ASIA" },
  { code: "IDN", name: "Indonesia", continent: "ASIA" },
  { code: "IRN", name: "Iran", continent: "ASIA" },
  { code: "IRQ", name: "Iraq", continent: "ASIA" },
  { code: "ISR", name: "Israel", continent: "ASIA" },
  { code: "JPN", name: "Japan", continent: "ASIA" },
  { code: "JOR", name: "Jordan", continent: "ASIA" },
  { code: "KAZ", name: "Kazakhstan", continent: "ASIA" },
  { code: "KWT", name: "Kuwait", continent: "ASIA" },
  { code: "KGZ", name: "Kyrgyzstan", continent: "ASIA" },
  { code: "LAO", name: "Laos", continent: "ASIA" },
  { code: "LBN", name: "Lebanon", continent: "ASIA" },
  { code: "MYS", name: "Malaysia", continent: "ASIA" },
  { code: "MDV", name: "Maldives", continent: "ASIA" },
  { code: "MNG", name: "Mongolia", continent: "ASIA" },
  { code: "MMR", name: "Myanmar", continent: "ASIA" },
  { code: "NPL", name: "Nepal", continent: "ASIA" },
  { code: "PRK", name: "North Korea", continent: "ASIA" },
  { code: "OMN", name: "Oman", continent: "ASIA" },
  { code: "PAK", name: "Pakistan", continent: "ASIA" },
  { code: "PSE", name: "Palestine", continent: "ASIA" },
  { code: "PHL", name: "Philippines", continent: "ASIA" },
  { code: "QAT", name: "Qatar", continent: "ASIA" },
  { code: "SAU", name: "Saudi Arabia", continent: "ASIA" },
  { code: "SGP", name: "Singapore", continent: "ASIA" },
  { code: "KOR", name: "South Korea", continent: "ASIA" },
  { code: "LKA", name: "Sri Lanka", continent: "ASIA" },
  { code: "SYR", name: "Syria", continent: "ASIA" },
  { code: "TWN", name: "Taiwan", continent: "ASIA" },
  { code: "TJK", name: "Tajikistan", continent: "ASIA" },
  { code: "THA", name: "Thailand", continent: "ASIA" },
  { code: "TLS", name: "Timor-Leste", continent: "ASIA" },
  { code: "TKM", name: "Turkmenistan", continent: "ASIA" },
  { code: "ARE", name: "United Arab Emirates", continent: "ASIA" },
  { code: "UZB", name: "Uzbekistan", continent: "ASIA" },
  { code: "VNM", name: "Vietnam", continent: "ASIA" },
  { code: "YEM", name: "Yemen", continent: "ASIA" },
  // AFRICA
  { code: "DZA", name: "Algeria", continent: "AFRICA" },
  { code: "AGO", name: "Angola", continent: "AFRICA" },
  { code: "BEN", name: "Benin", continent: "AFRICA" },
  { code: "BWA", name: "Botswana", continent: "AFRICA" },
  { code: "BFA", name: "Burkina Faso", continent: "AFRICA" },
  { code: "BDI", name: "Burundi", continent: "AFRICA" },
  { code: "CPV", name: "Cape Verde", continent: "AFRICA" },
  { code: "CMR", name: "Cameroon", continent: "AFRICA" },
  { code: "CAF", name: "Central African Republic", continent: "AFRICA" },
  { code: "TCD", name: "Chad", continent: "AFRICA" },
  { code: "COM", name: "Comoros", continent: "AFRICA" },
  { code: "COD", name: "Democratic Republic of the Congo", continent: "AFRICA" },
  { code: "COG", name: "Republic of the Congo", continent: "AFRICA" },
  { code: "CIV", name: "Ivory Coast", continent: "AFRICA" },
  { code: "DJI", name: "Djibouti", continent: "AFRICA" },
  { code: "EGY", name: "Egypt", continent: "AFRICA" },
  { code: "GNQ", name: "Equatorial Guinea", continent: "AFRICA" },
  { code: "ERI", name: "Eritrea", continent: "AFRICA" },
  { code: "SWZ", name: "Eswatini", continent: "AFRICA" },
  { code: "ETH", name: "Ethiopia", continent: "AFRICA" },
  { code: "GAB", name: "Gabon", continent: "AFRICA" },
  { code: "GMB", name: "Gambia", continent: "AFRICA" },
  { code: "GHA", name: "Ghana", continent: "AFRICA" },
  { code: "GIN", name: "Guinea", continent: "AFRICA" },
  { code: "GNB", name: "Guinea-Bissau", continent: "AFRICA" },
  { code: "KEN", name: "Kenya", continent: "AFRICA" },
  { code: "LSO", name: "Lesotho", continent: "AFRICA" },
  { code: "LBR", name: "Liberia", continent: "AFRICA" },
  { code: "LBY", name: "Libya", continent: "AFRICA" },
  { code: "MDG", name: "Madagascar", continent: "AFRICA" },
  { code: "MWI", name: "Malawi", continent: "AFRICA" },
  { code: "MLI", name: "Mali", continent: "AFRICA" },
  { code: "MRT", name: "Mauritania", continent: "AFRICA" },
  { code: "MUS", name: "Mauritius", continent: "AFRICA" },
  { code: "MAR", name: "Morocco", continent: "AFRICA" },
  { code: "MOZ", name: "Mozambique", continent: "AFRICA" },
  { code: "NAM", name: "Namibia", continent: "AFRICA" },
  { code: "NER", name: "Niger", continent: "AFRICA" },
  { code: "NGA", name: "Nigeria", continent: "AFRICA" },
  { code: "RWA", name: "Rwanda", continent: "AFRICA" },
  { code: "STP", name: "São Tomé and Príncipe", continent: "AFRICA" },
  { code: "SEN", name: "Senegal", continent: "AFRICA" },
  { code: "SLE", name: "Sierra Leone", continent: "AFRICA" },
  { code: "SOM", name: "Somalia", continent: "AFRICA" },
  { code: "ZAF", name: "South Africa", continent: "AFRICA" },
  { code: "SSD", name: "South Sudan", continent: "AFRICA" },
  { code: "SDN", name: "Sudan", continent: "AFRICA" },
  { code: "TZA", name: "Tanzania", continent: "AFRICA" },
  { code: "TGO", name: "Togo", continent: "AFRICA" },
  { code: "TUN", name: "Tunisia", continent: "AFRICA" },
  { code: "UGA", name: "Uganda", continent: "AFRICA" },
  { code: "ZMB", name: "Zambia", continent: "AFRICA" },
  { code: "ZWE", name: "Zimbabwe", continent: "AFRICA" },
  // NORTH AMERICA
  { code: "ATG", name: "Antigua and Barbuda", continent: "NORTH_AMERICA" },
  { code: "BHS", name: "Bahamas", continent: "NORTH_AMERICA" },
  { code: "BRB", name: "Barbados", continent: "NORTH_AMERICA" },
  { code: "BLZ", name: "Belize", continent: "NORTH_AMERICA" },
  { code: "CAN", name: "Canada", continent: "NORTH_AMERICA" },
  { code: "CRI", name: "Costa Rica", continent: "NORTH_AMERICA" },
  { code: "CUB", name: "Cuba", continent: "NORTH_AMERICA" },
  { code: "DMA", name: "Dominica", continent: "NORTH_AMERICA" },
  { code: "DOM", name: "Dominican Republic", continent: "NORTH_AMERICA" },
  { code: "SLV", name: "El Salvador", continent: "NORTH_AMERICA" },
  { code: "GRD", name: "Grenada", continent: "NORTH_AMERICA" },
  { code: "GTM", name: "Guatemala", continent: "NORTH_AMERICA" },
  { code: "HTI", name: "Haiti", continent: "NORTH_AMERICA" },
  { code: "HND", name: "Honduras", continent: "NORTH_AMERICA" },
  { code: "JAM", name: "Jamaica", continent: "NORTH_AMERICA" },
  { code: "MEX", name: "Mexico", continent: "NORTH_AMERICA" },
  { code: "NIC", name: "Nicaragua", continent: "NORTH_AMERICA" },
  { code: "PAN", name: "Panama", continent: "NORTH_AMERICA" },
  { code: "KNA", name: "Saint Kitts and Nevis", continent: "NORTH_AMERICA" },
  { code: "LCA", name: "Saint Lucia", continent: "NORTH_AMERICA" },
  { code: "VCT", name: "Saint Vincent and the Grenadines", continent: "NORTH_AMERICA" },
  { code: "TTO", name: "Trinidad and Tobago", continent: "NORTH_AMERICA" },
  { code: "USA", name: "United States", continent: "NORTH_AMERICA" },
  // SOUTH AMERICA
  { code: "ARG", name: "Argentina", continent: "SOUTH_AMERICA" },
  { code: "BOL", name: "Bolivia", continent: "SOUTH_AMERICA" },
  { code: "BRA", name: "Brazil", continent: "SOUTH_AMERICA" },
  { code: "CHL", name: "Chile", continent: "SOUTH_AMERICA" },
  { code: "COL", name: "Colombia", continent: "SOUTH_AMERICA" },
  { code: "ECU", name: "Ecuador", continent: "SOUTH_AMERICA" },
  { code: "GUY", name: "Guyana", continent: "SOUTH_AMERICA" },
  { code: "PRY", name: "Paraguay", continent: "SOUTH_AMERICA" },
  { code: "PER", name: "Peru", continent: "SOUTH_AMERICA" },
  { code: "SUR", name: "Suriname", continent: "SOUTH_AMERICA" },
  { code: "URY", name: "Uruguay", continent: "SOUTH_AMERICA" },
  { code: "VEN", name: "Venezuela", continent: "SOUTH_AMERICA" },
  // OCEANIA
  { code: "AUS", name: "Australia", continent: "OCEANIA" },
  { code: "FJI", name: "Fiji", continent: "OCEANIA" },
  { code: "KIR", name: "Kiribati", continent: "OCEANIA" },
  { code: "MHL", name: "Marshall Islands", continent: "OCEANIA" },
  { code: "FSM", name: "Micronesia", continent: "OCEANIA" },
  { code: "NRU", name: "Nauru", continent: "OCEANIA" },
  { code: "NZL", name: "New Zealand", continent: "OCEANIA" },
  { code: "PLW", name: "Palau", continent: "OCEANIA" },
  { code: "PNG", name: "Papua New Guinea", continent: "OCEANIA" },
  { code: "WSM", name: "Samoa", continent: "OCEANIA" },
  { code: "SLB", name: "Solomon Islands", continent: "OCEANIA" },
  { code: "TON", name: "Tonga", continent: "OCEANIA" },
  { code: "TUV", name: "Tuvalu", continent: "OCEANIA" },
  { code: "VUT", name: "Vanuatu", continent: "OCEANIA" },
];
